<?php

namespace Findo\Bundle\FinDoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ToDoItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToDoItemRepository extends EntityRepository
{
}
